#.travis.yml

sudo: required

dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - 8.9

branches:
  only:
    - master

before_install:
  - set -e
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm cache verify
  - npm prune
  - npm update

before_script:
  - npm install

script:
  - npm run test
  - npm run build

notifications:
  email:
    on_failure: change
    on_success: change
